#!/usr/local/bin/node

// Using the --request-- module which has since been depricated:
//
// let request = require("request");
// let Phrase = require("dgamboa-palindrome");
// let url = "https://cdn.learnenough.com/phrases.txt";
//
// request(url , function(error, response, body) {
//   body.split("\n").forEach(function(line) {
//     let phrase = new Phrase(line);
//     if (phrase.palindrome()) {
//       console.log("palindrome detected:", line);
//     }
//   });
// });

let urllib = require('urllib');
let Phrase = require("dgamboa-palindrome");
let url = "https://cdn.learnenough.com/phrases.txt";

urllib.request(url, { followRedirect: true }, function (err, data, res) {
  let lines = data.toString().split("\n");
  let palindromes = lines.filter(line => new Phrase(line).palindrome());
  palindromes.forEach(function(palindrome) {
      console.log("palindrome detected:", palindrome);
  });
});
